root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/gripello ./cmd/gripello"
entrypoint = "./tmp/gripello"
args_bin = ["serve", "--http=:8099"]
include_ext = ["go", "sql"]
exclude_dir = ["tmp", "data", "loadtest", "testdata"]
send_interrupt = true
kill_delay = "2s"

[log]
main_only = true
